[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Survival = "8a913413-2070-5976-9d4c-2b364fdc2f7f"

[compat]
Documenter = "~0.27"

[sources]
Survival = { path = ".." }
